// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppPath() {
  return window['go']['main']['App']['AppPath']();
}

export function CheckPort(arg1) {
  return window['go']['main']['App']['CheckPort'](arg1);
}

export function DirSize(arg1) {
  return window['go']['main']['App']['DirSize'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function ReadAll(arg1) {
  return window['go']['main']['App']['ReadAll'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
