// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppPath():Promise<string>;

export function DirSize(arg1:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;

export function ReadAll(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
